export const blogData = [
  {
    id: 1,
    title: "The Future of Web Development",
    summary: "Explore the exciting new trends shaping the web, from AI-powered interfaces to serverless architectures.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?web-development",
    author: "John Doe",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=JohnDoe",
    authorBio: "John is a seasoned web developer with a passion for cutting-edge technologies.",
    twitterHandle: "@johndoe_dev",
    date: "2025-08-27",
    categories: ["Web Development", "Future Tech"],
    readTime: "7 min read",
    likes: 123,
    views: 2400,
  },
  {
    id: 2,
    title: "A Deep Dive into React Hooks",
    summary: "Unlock the full potential of React with a comprehensive guide to custom hooks and their applications.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?react-hooks",
    author: "Jane Smith",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=JaneSmith",
    authorBio: "Jane is a front-end expert specializing in React and modern JavaScript frameworks.",
    twitterHandle: "@janesmith_dev",
    date: "2025-08-26",
    categories: ["React", "Frontend"],
    readTime: "10 min read",
    likes: 250,
    views: 5100,
  },
  {
    id: 3,
    title: "Getting Started with TypeScript",
    summary: "Learn how TypeScript can improve your JavaScript projects with static typing and enhanced tooling.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?typescript",
    author: "Peter Jones",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=PeterJones",
    authorBio: "Peter is a software engineer focused on building robust and scalable applications with TypeScript.",
    twitterHandle: "@peterjones_ts",
    date: "2025-08-25",
    categories: ["TypeScript", "Programming"],
    readTime: "8 min read",
    likes: 98,
    views: 1800,
  },
  {
    id: 4,
    title: "The Rise of AI in Everyday Applications",
    summary: "Discover how artificial intelligence is transforming various industries and daily routines.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?artificial-intelligence",
    author: "Alice Wonderland",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=AliceWonderland",
    authorBio: "Alice is an AI enthusiast and data scientist exploring the practical applications of machine learning.",
    twitterHandle: "@alice_ai",
    date: "2025-08-24",
    categories: ["AI", "Technology"],
    readTime: "12 min read",
    likes: 320,
    views: 7500,
  },
  {
    id: 5,
    title: "Mastering CSS Grid for Responsive Layouts",
    summary: "A comprehensive guide to building flexible and responsive web designs using CSS Grid.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?css-grid",
    author: "Bob Builder",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=BobBuilder",
    authorBio: "Bob is a UI/UX designer and front-end developer passionate about elegant and efficient layouts.",
    twitterHandle: "@bob_designs",
    date: "2025-08-23",
    categories: ["CSS", "Frontend", "Design"],
    readTime: "6 min read",
    likes: 85,
    views: 1500,
  },
  {
    id: 6,
    title: "Understanding Blockchain Technology",
    summary: "Demystifying the concepts behind blockchain, cryptocurrencies, and decentralized applications.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?blockchain",
    author: "Charlie Crypto",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=CharlieCrypto",
    authorBio: "Charlie is a blockchain expert and evangelist, exploring the future of decentralized systems.",
    twitterHandle: "@charlie_crypto",
    date: "2025-08-22",
    categories: ["Blockchain", "FinTech"],
    readTime: "15 min read",
    likes: 400,
    views: 9800,
  },
  {
    id: 7,
    title: "The Power of Serverless Functions",
    summary: "Leverage serverless computing to build scalable and cost-effective applications.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?serverless",
    author: "Diana Cloud",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=DianaCloud",
    authorBio: "Diana is a cloud architect specializing in serverless and microservices.",
    twitterHandle: "@diana_cloud",
    date: "2025-08-21",
    categories: ["Cloud", "Serverless"],
    readTime: "9 min read",
    likes: 180,
    views: 3200,
  },
  {
    id: 8,
    title: "Introduction to Machine Learning with Python",
    summary: "A beginner-friendly guide to machine learning concepts and implementation using Python.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?machine-learning-python",
    author: "Eve Data",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=EveData",
    authorBio: "Eve is a data scientist and educator, passionate about making machine learning accessible.",
    twitterHandle: "@eve_data",
    date: "2025-08-20",
    categories: ["Machine Learning", "Python"],
    readTime: "11 min read",
    likes: 290,
    views: 6000,
  },
  {
    id: 9,
    title: "Building RESTful APIs with Node.js and Express",
    summary: "Learn to create robust and scalable APIs using Node.js, Express, and MongoDB.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?nodejs-express",
    author: "Frank Backend",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=FrankBackend",
    authorBio: "Frank is a backend developer with expertise in Node.js and scalable API design.",
    twitterHandle: "@frank_backend",
    date: "2025-08-19",
    categories: ["Node.js", "Backend", "API"],
    readTime: "13 min read",
    likes: 150,
    views: 2800,
  },
  {
    id: 10,
    title: "Modern JavaScript Features You Should Know",
    summary: "Stay up-to-date with the latest ECMAScript features and write cleaner, more efficient code.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?javascript-features",
    author: "Grace Hopper",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=GraceHopper",
    authorBio: "Grace is a JavaScript evangelist and open-source contributor.",
    twitterHandle: "@grace_js",
    date: "2025-08-18",
    categories: ["JavaScript", "Programming"],
    readTime: "7 min read",
    likes: 210,
    views: 4500,
  },
  {
    id: 11,
    title: "DevOps for Beginners: A Practical Guide",
    summary: "Get started with DevOps principles and practices to streamline your development workflow.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?devops",
    author: "Henry DevOps",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=HenryDevOps",
    authorBio: "Henry is a DevOps engineer passionate about automation and continuous delivery.",
    twitterHandle: "@henry_devops",
    date: "2025-08-17",
    categories: ["DevOps", "Tools"],
    readTime: "14 min read",
    likes: 190,
    views: 3800,
  },
  {
    id: 12,
    title: "The Importance of UI/UX in Modern Web Apps",
    summary: "Understand how good UI/UX design can make or break your web application.",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    image: "https://source.unsplash.com/random/400x225?ui-ux",
    author: "Ivy Design",
    authorAvatar: "https://api.dicebear.com/7.x/lorelei/svg?seed=IvyDesign",
    authorBio: "Ivy is a UI/UX lead designer with a focus on user-centered design principles.",
    twitterHandle: "@ivy_design",
    date: "2025-08-16",
    categories: ["UI/UX", "Design"],
    readTime: "8 min read",
    likes: 270,
    views: 5500,
  },
];
